// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWGMoTxeMhfZejOP1xtVRBM3FqNkPlo5I',
    appId: '1:219301891752:web:09075e47c46546566e3c9d',
    messagingSenderId: '219301891752',
    projectId: 'localstics-96a0d',
    authDomain: 'localstics-96a0d.firebaseapp.com',
    storageBucket: 'localstics-96a0d.firebasestorage.app',
    measurementId: 'G-3LGGDMGJLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7aOd-Y4PLOdn-YHzIfiXVpxNswvPzLLo',
    appId: '1:219301891752:android:f3baacba13dc1c816e3c9d',
    messagingSenderId: '219301891752',
    projectId: 'localstics-96a0d',
    storageBucket: 'localstics-96a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8Q7nrnyx12BnvfpmBte88MluuxHriEM',
    appId: '1:219301891752:ios:91907be9d839b4306e3c9d',
    messagingSenderId: '219301891752',
    projectId: 'localstics-96a0d',
    storageBucket: 'localstics-96a0d.firebasestorage.app',
    iosBundleId: 'com.example.localstics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj8Q7nrnyx12BnvfpmBte88MluuxHriEM',
    appId: '1:219301891752:ios:91907be9d839b4306e3c9d',
    messagingSenderId: '219301891752',
    projectId: 'localstics-96a0d',
    storageBucket: 'localstics-96a0d.firebasestorage.app',
    iosBundleId: 'com.example.localstics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWGMoTxeMhfZejOP1xtVRBM3FqNkPlo5I',
    appId: '1:219301891752:web:21588bb1930aeb3f6e3c9d',
    messagingSenderId: '219301891752',
    projectId: 'localstics-96a0d',
    authDomain: 'localstics-96a0d.firebaseapp.com',
    storageBucket: 'localstics-96a0d.firebasestorage.app',
    measurementId: 'G-TKS961MTT5',
  );
}
